title: Qihang Sun's Homepage
description: A personal website of Qihang Sun
theme: just-the-docs

url: https://qihangsun1998.github.io/qihangs2

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
