title: Qihang Sun's Homepage
description: A personal website of Qihang Sun
theme: just-the-docs

url: https://qihangsun1998.github.io/qihangs2

search_enabled: true

nav_enabled: true

navigation: 
 - {title: "Research", file: "/research.md"}
 - {title: "Conferences", file: "/conferences.md"}
 - {title: "Personal", file: "/personal.md"}
